[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp
logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/2
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/2
stderr_logfile_maxbytes=0


# [program:laravel-queue]
# command=php /app/artisan queue:work --verbose --tries=3 --timeout=90
# directory=/app
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# stdout_logfile=/proc/self/fd/1
# stdout_logfile_maxbytes=0
# stderr_logfile=/proc/self/fd/2
# stderr_logfile_maxbytes=0

# ECS
[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work redis --sleep=3 --rest=1 --tries=3 --timeout=120 --backoff=10 --memory=256 --max-time=3600 --force --no-interaction
directory=/app
numprocs=1
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=10
stopasgroup=true
killasgroup=true
user=root
redirect_stderr=true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/2
stderr_logfile_maxbytes=0


[program:laravel-scheduler]
command=bash -c "while true; do php /app/artisan schedule:run --verbose --no-interaction; sleep 60; done"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/2
stderr_logfile_maxbytes=0
