version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile.local
            target: php
            args:
                - APP_ENV=${APP_ENV:-local}
        environment:
            - APP_ENV=${APP_ENV:-local}
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-homestead}
            - DB_USERNAME=${DB_USERNAME:-homestead}
            - DB_PASSWORD=${DB_PASSWORD:-secret}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8080:8080
        depends_on:
            - database
        networks:
            - laravel-network

    database:
        container_name: database
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-homestead}
            - MYSQL_USER=${DB_USERNAME:-homestead}
            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
            - TZ=${TZ:-Asia/Tokyo}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel-network

    scheduler:
        container_name: laravel-scheduler
        build:
            context: .
            dockerfile: Dockerfile.local
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - APP_ENV=${APP_ENV:-local}
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-homestead}
            - DB_USERNAME=${DB_USERNAME:-homestead}
            - DB_PASSWORD=${DB_PASSWORD:-secret}
        depends_on:
            - api
            - database
        networks:
            - laravel-network
        command: >
            sh -c "
              echo '⏳ Waiting for MySQL...';
              until nc -z database 3306; do sleep 2; done;
              echo '✅ MySQL ready. Starting Laravel scheduler...';
              # Vòng lặp chạy scheduler mỗi 60s
              while true; do
                php /app/artisan schedule:run --verbose --no-interaction;
                sleep 60;
              done
            "

volumes:
    db-data:


networks:
    laravel-network:
        driver: bridge
